name: Deploy Rules

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        run: python --version
      - name: Install dependencies
        run: python -m pip install requests
      - name: Install dependencies
        run: python -m pip install pyyaml
      - name: Deploy rules
        env:
          KIBANA_URL: ${{ secrets.KIBANA_URL }} ##replace with your SIEM tenant URL
          KIBANA_API_KEY: ${{ secrets.KIBANA_API_KEY }} ##replace with your SIEM tenant API key
        run: python scripts/deploy_rules.py
